Fix #3: Fix pagebreaks for after_docs
cvlabmiet/docx-combine pull request #4
Opened 2019-04-15 19:34 UTC by dvorotnev

Пример после исправления
[example_after.zip](https://github.com/cvlabmiet/docx-combine/files/3081803/example_after.zip)

2019-04-15 19:38 UTC, dvorotnev commented
Похоже `main_doc.element.body.append(element)` как то кешируется. В [интернетах](https://www.reddit.com/r/learnpython/comments/3nikbl/combining_word_documents_using_docx/)  pagebreak добавляют в добавляемый документ

2019-04-16 19:05 UTC, igsha requested changes
Надо ещё покопать

2019-04-16 19:05 UTC, igsha commented on docx-combine
> +    for i in range(len(after_docs) - 1):
а как быть, если `after_docs` нулевой длины?

2019-04-16 19:05 UTC, igsha commented on docx-combine
> -    if args.page_break:
можно сделать симметрично с `before_docs`, для этого надо добавлять один параграф с объектом run внутри, который содержит `WD_BREAK.PAGE`. Единственная проблема - параграф нельзя создать просто так, его нужно создавать через документ, а у документа есть только метод добавления параграфа в конец `add_paragraph`. Поэтому код примерно следующий:
```py
if args.page_break:
    p = docx.text.paragraph.Paragraph(doc.element.body._new_p(), None)
    p.add_run().add_break(docx.enum.text.WD_BREAK.PAGE)
    doc.element.body.insert(0, p._element)
```
здесь используется внутренее API (`_new_p` и `_element`). Другого способа я пока не нашёл. Есть ещё метод `doc.element.body._insert_p`, но он требует какой-то параметр. Можно поисследовать, что за параметр.

2019-04-16 19:05 UTC, igsha commented on docx-combine
> +    main_doc.add_page_break()
Если есть только `before_docs`, то будет пустая страница в конце документа.

2019-04-16 19:19 UTC, dvorotnev commented on docx-combine
> +    for i in range(len(after_docs) - 1):
По идее условие `if args.page_break and len(after_docs) > 1` решит обе проблемы с пустым списком. Так не норм?

2019-04-16 19:27 UTC, igsha commented on docx-combine
> +    for i in range(len(after_docs) - 1):
скорее уж `len(after_docs) != 0`, чтобы при наличии ровно одного документа вставился разрыв страниц в `main_doc`.
Да, можно так попробовать

2019-04-16 19:31 UTC, dvorotnev commented
@igsha, обновил

2019-04-17 05:06 UTC, igsha approved these changes

2019-04-17 05:06 UTC, merged